### ISSUE TITLE
text-shadow with multiple values generates erroneous error

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#584]
The following does not work:

```css
.gold-on-gold {
   text-shadow: rgba(0,0,0,0.1) -1px 0, rgba(0,0,0,0.1) 0 -1px,
   rgba(255,255,255,0.1) 1px 0, rgba(255,255,255,0.1) 0 1px,
   rgba(0,0,0,0.1) -1px -1px, rgba(255,255,255,0.1) 1px 1px; 
   color: gold;
   background: gold;
}
```
